# Generated by Django 5.0.7 on 2024-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_word', models.CharField(max_length=30, verbose_name='Первое слово названия')),
                ('thin_word', models.CharField(max_length=30, verbose_name='Второе слово')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
        ),
    ]
