# Generated by Django 5.0.7 on 2024-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Название сайта и контакты'},
        ),
        migrations.AddField(
            model_name='maininfo',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
